### ISSUE TITLE
Support CodeBuild CloudWatch Events

### ISSUE THREAD

**Issue by ericcj** [arabold/aws-to-slack#12]
https://docs.aws.amazon.com/codebuild/latest/userguide/sample-build-notifications.html#sample-build-notifications-ref

basic handler here:  https://hackernoon.com/monitor-your-aws-codebuilds-via-lambda-and-slack-ae2c621f68f1

**Comment by arabold** [comment]
Thanks. Should be easy to add with the given samples.

**Comment by arabold** [comment]
I've finally added this to the latest release. Any feedback would be appreciated!
