### ISSUE TITLE
Transform issue

### ISSUE THREAD

**Issue by freynolds** [arabold/aws-to-slack#23]
HI, I'm getting an issue when trying to create the transforms

Check the following transforms: ["AWS::Serverless-2016-10-31"]
You must use a change set to create this stack because it includes one or more transforms. The change set shows the resources that transforms add to your stack's template. Choose Create Change Set, check the resources that the transforms add, and then choose Execute. Learn more.

`Error creating change set: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [Handler] is invalid. 'CodeUri' requires Bucket and Key properties to be specified
`

I have no clue what to do

Thanks

**Comment by virtuoushub** [comment]
I will be opening a pull request to fix this issue, as I also ran into it and was able to resolve.

In the meantime I have documented the fix, below are my findings.

## offending code
```yaml
      CodeUri: !Sub 's3://aws-to-slack-${AWS::Region}/release.zip'
```
Source: [cloudformation.yaml:22](https://github.com/arabold/aws-to-slack/blob/b5befbb441891a1a175aed1921d6c6201e38d0e2/cloudformation.yaml#L22)

## suggested fix
```yaml
      CodeUri:
        Bucket: !Sub "aws-to-slack-${AWS::Region}"
        Key: release.zip
```

If you edit that file by hand, remember indentation really matters in `yaml` so be sure to lint.

**writing yaml** 😂 😂 😂 
![Writing YAML](https://pbs.twimg.com/media/Dm6ZVWuW4AcNeX0.jpg)
[Image source](https://twitter.com/caged/status/1039937162769096704)
