### ISSUE TITLE
Parser | - chart.js

### ISSUE THREAD

**Issue by acaacx** [arabold/aws-to-slack#27]
Any advice on how to use IAM role for the execution instead of  keys or secret? TIA

**Comment by arabold** [comment]
You do not need any specific AWS access keys or secret to _run_ `aws-to-slack`. If you run the CloudFormation script it sets up the Lambda with `CloudWatchReadOnlyAccess`. That should be it.

What issue do you see or trying to solve?

**Comment by acaacx** [comment]
its working now. The access issue appears to be related to my AWS account. Thank you.
