### ISSUE TITLE
Used the Deploy link - Package doesnt work

### ISSUE THREAD

**Issue by jvancleve007** [arabold/aws-to-slack#30]
So after deploying the template in US-East-1 I created a cloud watch pointed it to the topic pointed the topic to the handler automatic function that was created and added the hook url to the key value on the function but I see no alerts in the slack channel. Not sure what else I am missing to get this at least working than add to the development.

**Comment by thesuavehog** [comment]
Did you use the CloudFormation Stack to deploy it?
Have you tried publishing a test message (simple JSON) to the SNS topic your function is subscribed to to make sure that a basic message get through to your Slack channel?

**Comment by jvancleve007** [comment]
hmmm not sure what test information to use to send it as a test case.

**Comment by thesuavehog** [comment]
1. Login to Console > SNS > Topics
2. Select your Topic (checkbox beside it)
3. Publish to Topic
4. Test Message (using JSON Generator) like this:

![image](https://user-images.githubusercontent.com/44843779/49617699-a8091680-f983-11e8-83ac-b7abf0997504.png)

When I publish that it shows up in my Slack:

![image](https://user-images.githubusercontent.com/44843779/49617735-c4a54e80-f983-11e8-91c0-e36b421a1a2b.png)

**Comment by thesuavehog** [comment]
If that doesn't work - you probably don't have the SLACK_CHANNEL or SLACK_HOOK_URL environment variables for your Lambda function set right.

**Comment by homeyjd** [comment]
The CloudFormation template has changed significantly.  Closing unless additional feedback is given.

**Comment by jvancleve007** [comment]
Is this back up and working fully now?
