### ISSUE TITLE
Support for Code Pipeline notifications

### ISSUE THREAD

**Issue by thesuavehog** [arabold/aws-to-slack#31]
CodePipeline sends out events as code moves through the various stages. Adding support for CodePipeline compliments any CodeBuild & CodeDeploy support that already exists.

In particular, CodePipeline supports manual approval steps. Having these notifications pushed to Slack is extremely helpful for ensuring that people see the events and can easily (and quickly respond).

**Comment by arabold** [comment]
Thanks a lot for this contribution. I've merged it in and corrected a few minor ESLint issues. A new release 1.1.9 has been published.
