### ISSUE TITLE
Support for sending Cloudwatch Logs to Slack

### ISSUE THREAD

**Issue by e-moshaya** [arabold/aws-to-slack#33]
I have a cloutwatch logs filter and alarm on certain filter expressions. It would be nice to also send the like containing the filter expression to slack along with the metrics.

**Comment by homeyjd** [comment]
Good idea, and strangely difficult.  [CloudWatch.GetMetricData](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html) returns data about the metric, but it does not specify which service produces/logs to that metric.

There must be some kind of pattern or whitelist of metrics produced by LogFilters.  I suppose we could list every relevant [Logs.MetricFilter](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_MetricFilter.html) by calling [Logs.DescribeMetricFilters](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeMetricFilters.html) every time we encounter a CloudWatch event.  But that's not super efficient.

**Comment by nason** [comment]
I've done something like this in a custom slack notifier:

```js
const cloudwatch = new AWS.CloudWatch();
const cloudwatchlogs = new AWS.CloudWatchLogs();

// Generates start and end time ISO strings one hour before to one hour after the supplied timestamp
const makeCloudwatchTimeRange = (timestamp) => {
  const eventTime = new Date(timestamp)

  // For simplicity
  eventTime.setUTCMinutes(0)
  eventTime.setUTCSeconds(0)
  eventTime.setUTCMilliseconds(0)

  const eventHour = eventTime.getUTCHours()

  const startTime = new Date(eventTime)
  startTime.setUTCHours(eventHour - 1)

  const endTime = new Date(eventTime)
  endTime.setUTCHours(eventHour + 1)

  return {
    start: startTime.toISOString(),
    end: endTime.toISOString()
  }
}

// Look up alarm, then metric filter, to get filter pattern so that we can generate a relevant cloudwatch link
const alarmDescriptions = await cloudwatch.describeAlarms({
  AlarmNames: [Message.AlarmName],
  MaxRecords: 1
}).promise()
const alarmDescription = alarmDescriptions.MetricAlarms[0];
const { MetricName, Namespace } = alarmDescription;

const metricFilterDescriptions = await cloudwatchlogs.describeMetricFilters({
  metricName: MetricName,
  metricNamespace: Namespace,
  limit: 1
}).promise()
const metricFilterDescription = metricFilterDescriptions.metricFilters[0];
const { filterPattern, logGroupName } = metricFilterDescription;

const logsTimeRange = makeCloudwatchTimeRange(Record.Sns.Timestamp)
const logsLink = `https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=${logGroupName};filter=${encodeURIComponent(filterPattern)};start=${logsTimeRange.start};end=${logsTimeRange.end}`
```

Having this link has saved us a lot of time ☄️ 

@homeyjd you're totally right its not the most efficient, but do you think its worth it? What if it was opt-in somehow? Would you be open to a PR adding this?

**Comment by homeyjd** [comment]
I see -- so instead of providing the logs directly in the message, you're just linking to the Console.  

Adding a link takes up an insignificant amount of screen real estate vs. actually including logging lines.  This action could take place alongside the existing API calls, so it shouldn't slow down the Lambda handler.  Yea, that'd be great!

**Comment by homeyjd** [comment]
@nason I pushed this to my fork -- https://github.com/homeyjd/aws-to-slack/commit/d2b827835a6093365fe507df71afed9e089e78ed
It adds a link to the reason-text of the Slack message.  Is that what you were thinking?

**Comment by nason** [comment]
@homeyjd doooope! yes exactly

**Comment by homeyjd** [comment]
@e-moshaya Gonna close for now.
We've added a "See recent logs" link to the body text of the CloudWatch message that should take you to the AWS Console for your metric.

**Comment by homeyjd** [comment]
@e-moshaya We've added a link to "See recent logs" to the end of the text body.
https://github.com/arabold/aws-to-slack/blob/master/src/parsers/cloudwatch/index.js#L44
Hopefully this solves your use case?
Credit to @nason!
