### ISSUE TITLE
Parser for CloudFormation SNS messages

### ISSUE THREAD

**Issue by lorengordon** [arabold/aws-to-slack#36]
Was thinking it would be nice to get nicely formatted slack notifications for CloudFormation SNS events.

**Comment by lorengordon** [comment]
The CFN SNS notifications sends a message for _every_ resource within the stack. Basically, each line within the CFN stack's "Events" tab.

Probably mostly useful just to get notifications on the stack itself, rather than every stack resource. Looks like an appropriate filter for that will be to test if `LogicalResourceId == StackName`

**Comment by homeyjd** [comment]
Are the messages within the same SNS payload body, or delivered individually?  

A big drawback when implementing new patterns is not having an example! Can you offer an example of the full JSON package for a message you'd like to match?

**Comment by lorengordon** [comment]
Messages for each event are delivered individually. Figure I'll submit a pr myself soon enough. Was kind of using the issue as a reminder to follow up later. But I'll certainly add some examples messages tomorrow, when I get back to a computer! 😁

**Comment by homeyjd** [comment]
Gotcha.
FYI, I am soon merging https://github.com/arabold/aws-to-slack/pull/35
It brings a lot of improvements, including async/await support and for the first time, tests.
https://github.com/homeyjd/aws-to-slack/tree/master/test/parsers
Hopefully you'll find it easier to dev from :)

**Comment by lorengordon** [comment]
Sure thing, I can base from that branch if it makes things easier in the end!

**Comment by lorengordon** [comment]
Basic event format:

```
{
    "Records": [
        {
            "EventSource": "aws:sns",
            "EventVersion": "1.0",
            "EventSubscriptionArn": "arn:aws:sns:REGION:ACCOUNT_ID:ExampleTopic",
            "Sns": {
                "Type": "Notification",
                "MessageId": "95df01b4-ee98-5cb9-9903-4c221d41eb5e",
                "TopicArn": "arn:aws:sns:REGION:ACCOUNT_ID:TOPIC_NAME",
                "Subject": "AWS CloudFormation Notification",
                "Message": "StackId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/STACK_UUID'\nTimestamp='1970-01-01T00:00:00.000Z'\nEventId='EVENT_ID'\nLogicalResourceId='RESOURCE_ID'\nNamespace='ACCOUNT_ID'\nPhysicalResourceId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/STACK_UUID'\nPrincipalId='PRINCIPAL_ID'\nResourceProperties='null'\nResourceStatus='UPDATE_IN_PROGRESS'\nResourceStatusReason='User Initiated'\nResourceType='AWS::CloudFormation::Stack'\nStackName='STACK_NAME'\nClientRequestToken='null'\n",
                "Timestamp": "1970-01-01T00:00:00.000Z",
                "SignatureVersion": "1",
                "Signature": "EXAMPLE",
                "SigningCertUrl": "EXAMPLE",
                "UnsubscribeUrl": "EXAMPLE",
                }
            }
        }
    ]
}
```

It's the `Message` that contains the data we want to parse. It is a string of key=value pairs separated by `\n` newlines. I'll post some more examples of _just_ the Message content, split on newlines for readability.

Staring at enough of these, the events that seem of most interest for notification purposes are those where, in the `Message`, this condition is met: `LogicalResourceId === StackName`. The goal being to notify when an event is about the stack itself, rather than a resource within the stack. Other events could just be dropped/ignored. By including a link to the stack in the notification, a user can further investigate if they need to look into an issue.

Here's an example of a python-based parser for these events:

* https://github.com/guardian/cf-notify/blob/473e14521ccae7f382423d1574566406e7a96f5c/lambda_notify.py#L47

**Comment by lorengordon** [comment]
Here is the `Message` content from a few events that were all part of the same CloudFormation stack update. This update affected 6 resources, and generated 31 total SNS messages. Hence why I think notifying on _every_ message is overkill, and am looking to limit that to _just_ the messages about the stack itself. In the below examples, that would be the first and last messages.

Stack update event (UPDATE_IN_PROGRESS):

```
StackId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/1bff3bd0-8f10-11e7-8d95-500c28604ce6'
Timestamp='2019-01-19T14:40:38.306Z'
EventId='300f76f0-1bf8-11e9-bf02-123ad236a92a'
LogicalResourceId='STACK_NAME'
Namespace='ACCOUNT_ID'
PhysicalResourceId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/1bff3bd0-8f10-11e7-8d95-500c28604ce6'
PrincipalId='PRINCIPAL_ID'
ResourceProperties='null'
ResourceStatus='UPDATE_IN_PROGRESS'
ResourceStatusReason='User Initiated'
ResourceType='AWS::CloudFormation::Stack'
StackName='STACK_NAME'
ClientRequestToken='Console-ExecuteChangeSet-c40d42f5-3099-c0ab-c1bd-c5058f140ac0'
```

Resource within the stack (UPDATE_IN_PROGRESS):

```
StackId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/1bff3bd0-8f10-11e7-8d95-500c28604ce6'
Timestamp='2019-01-19T14:40:45.527Z'
EventId='AmiIdLookup-UPDATE_IN_PROGRESS-2019-01-19T14:40:45.527Z'
LogicalResourceId='AmiIdLookup'
Namespace='ACCOUNT_ID'
PhysicalResourceId='2019/01/06/[$LATEST]1f8593818f004299a3b80e8bc793ce5f'
ResourceProperties='JSON_ENCODED_STRING'
ResourceStatus='UPDATE_IN_PROGRESS'
ResourceStatusReason=''
ResourceType='Custom::AmiIdLookup'
StackName='STACK_NAME'
ClientRequestToken='Console-ExecuteChangeSet-c40d42f5-3099-c0ab-c1bd-c5058f140ac0'
```

Resource within the stack (UPDATE_COMPLETE):

```
StackId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/1bff3bd0-8f10-11e7-8d95-500c28604ce6'
Timestamp='2019-01-19T14:40:51.502Z'
EventId='AmiIdLookup-UPDATE_COMPLETE-2019-01-19T14:40:51.502Z'
LogicalResourceId='AmiIdLookup'
Namespace='ACCOUNT_ID'
PhysicalResourceId='2019/01/19/[$LATEST]527708be21cf464dbaad9d9dff9cd45d'
ResourceProperties='JSON_ENCODED_STRING'
ResourceStatus='UPDATE_COMPLETE'
ResourceStatusReason=''
ResourceType='Custom::AmiIdLookup'
StackName='STACK_NAME'
ClientRequestToken='Console-ExecuteChangeSet-c40d42f5-3099-c0ab-c1bd-c5058f140ac0'
```

Another resource within the stack (UPDATE_IN_PROGRESS):

```
StackId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/1bff3bd0-8f10-11e7-8d95-500c28604ce6'
Timestamp='2019-01-19T14:41:00.895Z'
EventId='LaunchConfig-UPDATE_IN_PROGRESS-2019-01-19T14:41:00.895Z'
LogicalResourceId='LaunchConfig'
Namespace='ACCOUNT_ID'
PhysicalResourceId='STACK_NAME-LaunchConfig-1SJ0H9L9CX942'
ResourceProperties='JSON_ENCODED_STRING'
ResourceStatus='UPDATE_IN_PROGRESS'
ResourceStatusReason='Requested update requires the creation of a new physical resource; hence creating one.'
ResourceType='AWS::AutoScaling::LaunchConfiguration'
StackName='STACK_NAME'
ClientRequestToken='Console-ExecuteChangeSet-c40d42f5-3099-c0ab-c1bd-c5058f140ac0'
```

Another resource within the stack (UPDATE_COMPLETE):

```
StackId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/1bff3bd0-8f10-11e7-8d95-500c28604ce6'
Timestamp='2019-01-19T14:41:02.204Z'
EventId='LaunchConfig-UPDATE_COMPLETE-2019-01-19T14:41:02.204Z'
LogicalResourceId='LaunchConfig'
Namespace='ACCOUNT_ID'
PhysicalResourceId='STACK_NAME-LaunchConfig-148RY084FH00Z'
ResourceProperties='JSON_ENCODED_STRING'
ResourceStatus='UPDATE_COMPLETE'
ResourceStatusReason=''
ResourceType='AWS::AutoScaling::LaunchConfiguration'
StackName='STACK_NAME'
ClientRequestToken='Console-ExecuteChangeSet-c40d42f5-3099-c0ab-c1bd-c5058f140ac0'
```

Stack update event (UPDATE_COMPLETE):

```
StackId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/1bff3bd0-8f10-11e7-8d95-500c28604ce6'
Timestamp='2019-01-19T15:23:26.550Z'
EventId='2ad499d0-1bfe-11e9-8d11-0e8cdcc47538'
LogicalResourceId='STACK_NAME'
Namespace='ACCOUNT_ID'
PhysicalResourceId='arn:aws:cloudformation:REGION:ACCOUNT_ID:stack/STACK_NAME/1bff3bd0-8f10-11e7-8d95-500c28604ce6'
PrincipalId='PRINCIPAL_ID'
ResourceProperties='null'
ResourceStatus='UPDATE_COMPLETE'
ResourceStatusReason=''
ResourceType='AWS::CloudFormation::Stack'
StackName='STACK_NAME'
ClientRequestToken='Console-ExecuteChangeSet-c40d42f5-3099-c0ab-c1bd-c5058f140ac0'
```

**Comment by lorengordon** [comment]
@homeyjd Alright, I'm having a bit more trouble following the new code than I had with the old code... In particular, there is now a `SNSParser` that looks to actually be posting the slack message? Before the parsers only ever returned the slack `message` and let `processIncoming` post it.

Further, the lambda handler is _also_ posting the slack message? What am I missing here?

`processIncoming` looks to still handle an empty message as an ignored event, but `SNSParser` does not (far as I can follow anyway).

Should I just wait on this until the async/await stuff is more fully tested and merged?

**Comment by homeyjd** [comment]
You're right, `SNSParser` is an oddball because SNS can deliver multiple messages.  So `SNSParser`  will perform the multi-broadcast and stop `processIncoming` _only if the messages are special enough to not be returned as a single message_.  Messages are still only delivered once.

In re-reading the code, I completely understand the confusion -- I didn't add many comments and could have done a better job at organization.  The primary flow is:
- most parsers only return the `attachments` array
- if this primary case is true, then append attachments to a known-list
- if only attachments were returned, then it's safe to delegate back to `processIncoming` by returning a single object https://github.com/homeyjd/aws-to-slack/blob/master/src/parsers/sns.js#L42 (this makes the parsers testable)
- otherwise, each individual message must be sent and `processIncoming` should be cancelled

Not sure what you mean re: empty messages.  If you're referring to `processIncoming`, the use case is "how does a parser _stop_ `processIncoming` from waterfaling to the next parser?"

I have 3 instances of this code running in 2 accounts and it's working well for me so far.  What additional tests would you like to see to increase your own confidence?

**Comment by lorengordon** [comment]
> Not sure what you mean re: empty messages. If you're referring to processIncoming, the use case is "how does a parser stop processIncoming from waterfaling to the next parser?"

I am referring to the case where a parser has accepted a message but chosen to ignore it. Not so much meaning that it _halts_ processIncoming from waterfalling to another parser, as stopping _only_ the `generic` parser from picking it up. In the original version, this was handled here:

* https://github.com/arabold/aws-to-slack/blob/master/src/index.js#L49-L52

In your fork, I _think_ it is handled here:

* https://github.com/homeyjd/aws-to-slack/blob/master/src/index.js#L47-L50

Though, it's a bit more confusing to me because there are a couple layers of if statements. That link being the first, and the other being in the exported handler. (Also, returning `true` for this case is confusing semantically.)

I don't see how to trigger that logic path in `SNSParser` at the moment. What happens when the `handleMessage` return is empty?

---

I think I grok what the goal was with supporting SNS events with multiple records. But, `SNSParser` is handling multiple concerns now. Before, the parsers were just dealing with parsing the event to construct the slack message, and it was up to `processIncoming` to post it to slack. Now, for `SNSParser` at least, the parser is also itself posting to slack. I fail to see how that makes things more testable. It _ought_ to have been rather straightforward to test any of the parsers before... as any given input would have been rejected or returned a predictable slack message. That's about as easy as a test gets. Now there are more paths to consider for `SNSParser`...

What do you think about perhaps letting the lambda handler continue to deal with posting to slack? `SNSParser` could then just process the SNS records, gather the slack messages/attachments, and return them to the handler. The handler could then deal with posting the messages to slack.

---

The way `SNSParser` sends only the `Message` property to parsers but otherwise ignores other properties of the record also feels odd. Sometimes the `Message` is just a string-blob that requires processing, as is the case with the beanstalk parser (and this cloudformation parser). For the parsers to be able to early-reject the record with minimal processing, they need the `Subject` property. Perhaps just send through the entire record, or at least the `Sns` object?

---

Anyway, I've clearly gotten away from what I'm actually trying to implement here. I think for now I'm just going to write the cloudformation parser with it's own `parse` function. I can re-target as some of these questions get sorted and the eventual implementation becomes more clear.

**Comment by lorengordon** [comment]
Something else... When SNS does deliver multiple records in one event, are the records all of the same type? Isn't every parser that extends `SNSParser` processing every record in the SNS event? Would it not be better to iterate over the `Records` array, if present, in `processIncoming` and handle multiple records there?

Edit: No, I see, it's mapping _this_ parser over every record. Got it.

**Comment by homeyjd** [comment]
That was a lot to unpack...  My overall goals are:
- _Simplify parsers so that it's easier to contribute to the project._
Each SNS parser has to unpack and deserialize the Sns.Message object separately.  SNS is a common event packetizer, so it makes sense to have an abstract class that makes it easier to handle this.
- _Never drop data._
Honestly, in my experience I haven't seen SNS deliver more than one record at a time.  However, the data structure does not enforce that constraint.  So I'm coding defensively.

Seems `SNSParser` is causing you some duress.  I thought it was a decent first-pass, but no-matter.  You're right, my second goal isn't accomplished if `.Records[0]` and `.Records[1]` are differing types.  I've moved the logic to the top-level to accomplish this goal.  
https://github.com/homeyjd/aws-to-slack/commit/e085f715613b007b3e8046c40864bb4792160f33

Regarding my first goal, I think I've been able to simplify just about every parser. Logic LOC / Halstead effort is significantly down, maintainability is slightly up, and importantly Core Size is down implying more code-reuse.  I hope these changes make your parser implementations easier to read.

If it makes more sense to you to implement the `parse()` method instead of extending SNSParser, then go for it!  If you return something truthy, it means you've "handled" the message; if that truthy value is a non-empty object, it will be sent to Slack.

**Comment by lorengordon** [comment]
I realize I was probably coming across as more critical/negative than I intended. My apologies for that. This is a great library, and I do find the async/await syntax easier to understand in the lambda handler. 

> SNS is a common event packetizer, so it makes sense to have an abstract class that makes it easier to handle this

No argument there. The SNSParser abstract class is a great idea to reduce the burden when writing SNS-based parsers.

> If it makes more sense to you to implement the parse() method instead of extending SNSParser, then go for it!

Heh. Won't need to with you updating the code this quickly!

How are you running tests locally? Any particular node.js version requirement?

**Comment by homeyjd** [comment]
> How are you running tests locally?

I've been running `npm install && npm test` referencing [package.json](https://github.com/homeyjd/aws-to-slack/blob/master/package.json#L10).

> Any particular node.js version requirement?

I updated the [engine requirement](https://github.com/homeyjd/aws-to-slack/blob/master/package.json#L6) to the [Lambda version in the CF template](https://github.com/homeyjd/aws-to-slack/blob/master/cloudformation.yaml#L51).  Node 8 provides async/await, so 8 would be the lowest acceptable version.
