### ISSUE TITLE
CodePipeline Notifications Howto

### ISSUE THREAD

**Issue by nason** [arabold/aws-to-slack#37]
Thanks for this awesome project!

It looks like the CodePipeline parser is set up to parse SNS messages.

I set up CodePipeline events through CloudWatch Events (https://docs.aws.amazon.com/codepipeline/latest/userguide/detect-state-changes-cloudwatch-events.html), not through SNS. 

When I have my CloudWatch Event rule trigger the aws-to-slack lambda it just sends the raw message.

Is there another way to do it? It would be great if this could parse Cloudwatch Events for CodePipeline and send nicely formatted Slack notifications.

**Comment by homeyjd** [comment]
Sounds like a good idea. The big hurdle in accomplishing new parsers is not having examples! 
 Can you provide the full JSON packet you received?

**Comment by nason** [comment]
Ok great. The events look like:

```
{
 "version": "0",
 "id": "f3c0d851-b344-4c84-0a68-d8b9fb67b430",
 "detail-type": "CodePipeline Pipeline Execution State Change",
 "source": "aws.codepipeline",
 "account": "111111111111",
 "time": "2019-01-22T16:38:24Z",
 "region": "us-east-1",
 "resources": [
   "arn:aws:codepipeline:us-east-1:111111111111:my-pipeline"
 ],
 "detail": {
   "pipeline": "my-pipeline",
   "execution-id": "b938328a-79f5-484b-bff3-a412c69ef1eb",
   "state": "STARTED",
   "version": 2
 }
}
```

**Comment by homeyjd** [comment]
Seems easy enough. I've added a v1 of the parser to my PR https://github.com/arabold/aws-to-slack/pull/35.  
https://github.com/homeyjd/aws-to-slack/commit/accaa7c83623e2f372adfb17633bbf4526ac66a4
Will merge back to arabold/master soon.

**Comment by connor-tyndall** [comment]
@homeyjd I tested the latest changes from CloudWatch Event (CodePipeline trigger) to this Lambda and getting the following syntax error:

> Syntax error in module 'src/index': SyntaxError
async processEvent(event) {
^^^^^^^^^^^^
SyntaxError: Unexpected identifier
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

**Comment by lorengordon** [comment]
@connor-tyndall What is your lambda function's runtime version? If it's not node8 (or later), you'll get a syntax error like that...

**Comment by homeyjd** [comment]
Great point, @lorengordon.  This is a big change for this repo, upgrading from Lambda/Node v6 to v8.  Maybe we should add a notice to the `Readme.md`?

**Comment by nason** [comment]
Great work! tyvm @homeyjd  

Using #39 I've been able to deploy my own stack from source and test this out. Smooth sailing and lovely pipeline notifications so far!
