### ISSUE TITLE
Issue with signin link in message footer

### ISSUE THREAD

**Issue by nason** [arabold/aws-to-slack#40]
<img width="610" alt="screen shot 2019-01-26 at 2 37 24 pm" src="https://user-images.githubusercontent.com/4752318/51791949-e26b8480-2178-11e9-9915-4239244e2611.png">

It seems like the footer text is being truncated before the link is parsed, and ends up looking like this for me.

Would you be open to a PR to remove the signin link from this footer?

**Comment by homeyjd** [comment]
Oh man, you're right!  `sns.js` makes the assumption that `mkdwn_in:[]` contains "footer".  Bad assumption!
https://github.com/arabold/aws-to-slack/blob/master/src/parsers/sns.js#L105
This should fix? https://github.com/arabold/aws-to-slack/commit/6cd0236c97096c0bd64ff1d2308a3a14ef71b2ea

**Comment by homeyjd** [comment]
I'm an idiot...  Slack treats URLs separately from Markdown https://api.slack.com/docs/message-formatting#linking_to_urls
Now I'm very confused why the URL isn't working for you, but is for me:
<img width="498" alt="screen shot 2019-01-26 at 1 00 11 pm" src="https://user-images.githubusercontent.com/1088185/51792728-57838d80-216a-11e9-862c-5d1e0b57f5eb.png">

**Comment by nason** [comment]
Ahh I think its being truncated

> Limited to 300 characters, and may be truncated further when displayed to users in environments with limited screen real estate.

https://api.slack.com/docs/message-attachments#footer

**Comment by homeyjd** [comment]
Darn that fine print!  So I'm guessing that 300 characters is _including the link URL_, not just visible characters?

Thanks for the link!  
https://github.com/homeyjd/aws-to-slack/commit/807cbda7975fb1b21b45f36af8af387fe60d03d8

FYI, for what it's worth, the reason for the "Sign In" link is for those of us who manage multiple AWS accounts.  If I receive an alert for an account that isn't my last-logged-in account, the link appears to not work.  Hitting the "Sign In" link will force a re-auth and redirect to the correct place.

**Comment by nason** [comment]
Thanks for the fix! I deployed from master and it looks good
