### ISSUE TITLE
Formatting not being applied to messages

### ISSUE THREAD

**Issue by jtwp** [arabold/aws-to-slack#44]
Should all the notifications for the supported resources come through formatted and coloured? Only, I get all the notifications, but only CloudWatch Alarms (CPU etc) are correctly formatted. All others come through, as what seems to be, the raw json format. I have tried all the supported formats, but can't seem to get them to display nicely.

Example of GuardDuty notifications:
![guardduty](https://user-images.githubusercontent.com/4807091/52346587-ce950d80-2a17-11e9-8e95-2066898782e9.png)

**Comment by virtuoushub** [comment]
I am also seeing this issue after I configured CodePipeline via a CloudWatch Event Rule.

CodeBuild behaves as expected using the same technique (CloudWatch Event Rule).

**Comment by homeyjd** [comment]
The largest challenge here is understanding the myriad of event key/structures in the AWS ecosystem.
The current GuardDuty parser looks for `event.service.serviceName`.  It seems your events do not match this test.
https://github.com/arabold/aws-to-slack/blob/master/src/parsers/guardduty.js#L12

Can you please post an example event so we can add a test case and extend the parser?

**Comment by homeyjd** [comment]
@virtuoushub The CodePipeline-CloudWatch parser uses `event.source="aws.codepipeline"`.
https://github.com/arabold/aws-to-slack/blob/master/src/parsers/codepipelineCloudWatch.js#L10

Are you seeing differently-formatted messages?  Can you post an example message?

**Comment by virtuoushub** [comment]
@homeyjd, maybe I miss-configured my cloudwatch event rule. Not trying to hijack this issue, please let me know if you'd rather I open a new one.

**Event pattern:**
```
{
  "source": [
    "aws.codepipeline"
  ]
}
```
**example message 1**
```json
{
 "version": "0",
 "id": "d2ec51b0-119e-bd9f-9602-81679b3a0dcf",
 "detail-type": "CodePipeline Action Execution State Change",
 "source": "aws.codepipeline",
 "account": "012345678901",
 "time": "2019-02-20T16:34:46Z",
 "region": "us-east-1",
 "resources": [
   "arn:aws:codepipeline:us-east-1:012345678901:foo-pipeline"
 ],
 "detail": {
   "pipeline": "foo-pipeline",
   "execution-id": "4b02612a-1b13-4d4f-bc78-1fb45dc6376e",
   "stage": "FooStage",
   "action": "PackageExport",
   "state": "STARTED",
   "region": "us-east-1",
   "type": {
     "owner": "AWS",
     "provider": "CodeBuild",
     "category": "Build",
     "version": "1"
   },
   "version": 3
 }
}
```
**example message 2**
```json
{
 "version": "0",
 "id": "d5720ca3-88c3-09bf-013d-3579df74012a",
 "detail-type": "CodePipeline Action Execution State Change",
 "source": "aws.codepipeline",
 "account": "012345678901",
 "time": "2019-02-20T16:34:45Z",
 "region": "us-east-1",
 "resources": [
   "arn:aws:codepipeline:us-east-1:012345678901:foo-pipeline"
 ],
 "detail": {
   "pipeline": "foo-pipeline",
   "execution-id": "4b02612a-7b14-4d4f-bc78-1fb45dc6376e",
   "stage": "FooStage",
   "action": "Staging-Approve",
   "state": "SUCCEEDED",
   "region": "us-east-1",
   "type": {
     "owner": "AWS",
     "provider": "Manual",
     "category": "Approval",
     "version": "1"
   },
   "version": 3
 }
}
```

**Comment by homeyjd** [comment]
@virtuoushub You guys are talking about different parsers, so it could be a different issue.  But seems the Generic parser shouldn't be handling either of your use cases.

I added your first example event and all tests still pass https://github.com/arabold/aws-to-slack/commit/d9ca09cfd4b4399f55bcdb71e439ccc59b605591

Is your Lambda using latest version via `master` branch?  You can use `make package` to re-create the release.zip file and then manually upload to Lambda.

**Comment by stevemac007** [comment]
I've been working on adding the GuardDuty support - all of my testing has been from simulated events - I just noticed in my case that  I forgot the SNS wrapper that sends the message needs to be processed.  I'm testing the fixes at the moment and hope to have a new pull request to resolve that issue shortly.

**Comment by homeyjd** [comment]
Merged PR https://github.com/arabold/aws-to-slack/pull/47.  Should hopefully solve unformatted text from GuardDuty.  Thanks @stevemac007!

**Comment by chriswynnyk** [comment]
I was experiencing the same issue. I followed README.md install steps as-is (installing via the link) and manually created a Codepipeline event trigger. Messages came through, unparsed.

I was able to get things working by manually compiling with `make package` and uploading, then switching the execution environment from node 6.x -> node 8.x (otherwise execution fails on `await` syntax).

**Comment by homeyjd** [comment]
@chriswynnyk If you installed using the "Launch Stack" button, then you're using code over a year old.  Only @arabold has access to the S3 buckets, so we haven't been able to update the quick-install option.

I've updated the Readme with hopefully more-helpful steps: https://github.com/arabold/aws-to-slack#try
