### ISSUE TITLE
1.1.9 release.zip on S3 not applying formatting to CodePipeline messages

### ISSUE THREAD

**Issue by virtuoushub** [arabold/aws-to-slack#46]
https://s3.amazonaws.com/aws-to-slack-us-east-1/release.zip results in the behavior noted in [my comment](https://github.com/arabold/aws-to-slack/issues/44#issuecomment-465715791).

I tried building from d9ca09cfd4b4399f55bcdb71e439ccc59b605591 and uploading that as 
@homeyjd [suggested.](https://github.com/arabold/aws-to-slack/issues/44#issuecomment-465719255)

The build artifact resulted in an error in CloudWatch:

```
Syntax error in module 'src/index': SyntaxError async processEvent(event) { ^^^^^^^^^^^^ SyntaxError: Unexpected identifier at createScript (vm.js:56:10) at Object.runInThisContext (vm.js:97:10) at Module._compile (module.js:542:28) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) 
```

@homeyjd, is there a different git commit that I can try? I also want to test building on a different machine just to rule out my build environment.

Resultant local build zip: [release.zip](https://github.com/arabold/aws-to-slack/files/2886672/release.zip)

**build output**
[make-package-output.log](https://github.com/arabold/aws-to-slack/files/2894944/make-package-output.log)

**[edited for clarity, length and readability]**

**Comment by homeyjd** [comment]
Anyone with access could run `make publish` to upload the S3.  I believe the only one with access to the S3 buckets is @arabold.  

> That did not work for me.

Are you saying no change in behavior?  Next debugging steps would be to investigate if there are any errors in the CloudWatch logs for the Lambda function.  Minimally you'll see which parser was selected by the handler.  Any insights there?

**Comment by virtuoushub** [comment]
Sorry for not being clear. I will update the original issue description for clarity.

When I built d9ca09cfd4b4399f55bcdb71e439ccc59b605591 from source and manually uploaded the zip, there were errors in CloudWatch:

```
Syntax error in module 'src/index': SyntaxError async processEvent(event) { ^^^^^^^^^^^^ SyntaxError: Unexpected identifier at createScript (vm.js:56:10) at Object.runInThisContext (vm.js:97:10) at Module._compile (module.js:542:28) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) 
```
Because it was not a real [release](https://github.com/arabold/aws-to-slack/releases) I did not go into further detail.

Your tip about debugging is a good one, when I get some time I will just edit the source from https://s3.amazonaws.com/aws-to-slack-us-east-1/release.zip to see which parser was selected. Will post any insights here.

**Comment by homeyjd** [comment]
Gotcha, thank you for that error detail!
Only reason to see a syntax error would be because the Lambda is set to Node v6 instead of Node v8. This was changed just a couple months ago in this repo to take advantage of async/await. 

Try changing the Lambda runtime and using your built release.zip.

**Comment by virtuoushub** [comment]
@homeyjd, great tip, switching to Node v8 resulted in a working Lambda execution for the d9ca09cfd4b4399f55bcdb71e439ccc59b605591 [local build](https://github.com/arabold/aws-to-slack/files/2886672/release.zip)
which also resulted in a working CodePipeline message:

![image](https://user-images.githubusercontent.com/4303638/53257596-8f61f000-3698-11e9-9560-0c7f3686d97c.png)

I am going to close this issue as the expected behavior is [1.1.9](https://github.com/arabold/aws-to-slack/releases/tag/1.1.9) does not apply CodePipeline formatting.

A new release (2.0.0? as Node v6 => v8 is seemingly a breaking change) that consists of the latest from master branch (from at least d9ca09cfd4b4399f55bcdb71e439ccc59b605591 and on as that is what I tested) will have CodePipeline messages formatted correctly.
