### ISSUE TITLE
Cloudwatch notification didnt include charts for me

### ISSUE THREAD

**Issue by claylehman** [arabold/aws-to-slack#48]
I set this up and get a notification in the slack channel, but no chart is include.  the chart was very important to us.
![image](https://user-images.githubusercontent.com/40699759/53986360-fb5a4480-40eb-11e9-8df7-edfb143764ca.png)

**Comment by claylehman** [comment]
It may be worth noting that the alert is for ECS CPU metrics:
[ "AWS/ECS", "CPUUtilization", "ClusterName", "filethis-ecs-production", "ServiceName", "fetcher-aio", { "stat": "Maximum" } ],

**Comment by homeyjd** [comment]
Thanks for the bug-report.  You probably launched this from the "Launch Stack" button in the Readme?  The title of your example message doesn't match what is on master, so I'm guessing it's the last Zip-release: https://github.com/arabold/aws-to-slack/blob/master/src/parsers/cloudwatch/index.js#L60

Unfortunately, only @arabold has access to the S3 buckets, so we haven't been able to produce a new Zip release yet.

However, you can update your Lambda function code by cloning this repo and running:
`make package lambda-update LAMBDA_NAME="<your_lambda_name>"`.

If you still notice issues with the chart, can you please post logs from Lambda/CloudWatch so we can help?

**Comment by claylehman** [comment]
I used the readme and the cloudformation template as an example, but created mine in terraform.  I downloaded the release.zip from s3 and used that.  I will try pulling the repo and building the latest, and get back to you.  Thanks for the quick response!

**Comment by lorengordon** [comment]
If you're using terraform, give our module a try. It's just a wrapper around this package that makes it rather easy to deploy.

https://github.com/plus3it/terraform-aws-slack-notifier

**Comment by claylehman** [comment]
@homeyjd is there a way to build the release.zip? i am guessing the command you pasted will use aws CLI and try and update my lambda?

**Comment by claylehman** [comment]
that was a lazy question...i see the instructions in the readme to make a new release.zip

**Comment by claylehman** [comment]
manually building the latest from master, still doesnt show a chart for my use case.
![image](https://user-images.githubusercontent.com/40699759/54004792-e77f0480-4124-11e9-9a17-086fb6eae917.png)

**Comment by claylehman** [comment]
Cloudwatch logs:

START RequestId: f796e599-daa2-4186-8a78-42f190b9a578 Version: $LATEST
2019-03-08T03:02:48.233Z	f796e599-daa2-4186-8a78-42f190b9a578	Incoming Message:
{
    "Records": [
        {
            "EventSource": "aws:sns",
            "EventVersion": "1.0",
            "EventSubscriptionArn": "arn:aws:sns:us-west-1:287332224621:Cloudwatch-Alarm-Critical:9a2f4edd-dfeb-45f6-b4be-0ee61734ed61",
            "Sns": {
                "Type": "Notification",
                "MessageId": "a939c016-64f6-577b-a0f3-94edb961362f",
                "TopicArn": "arn:aws:sns:us-west-1:287332224621:Cloudwatch-Alarm-Critical",
                "Subject": "ALARM: \"PROD-fetcher-cpu-max\" in US West (N. California)",
                "Message": "{\"AlarmName\":\"PROD-fetcher-cpu-max\",\"AlarmDescription\":\"This metric monitors fetcher CPU max\",\"AWSAccountId\":\"287332224621\",\"NewStateValue\":\"ALARM\",\"NewStateReason\":\"Threshold Crossed: 1 datapoint [165.95022984554893 (08/03/19 03:01:00)] was greater than the threshold (50.0).\",\"StateChangeTime\":\"2019-03-08T03:02:47.414+0000\",\"Region\":\"US West (N. California)\",\"OldStateValue\":\"OK\",\"Trigger\":{\"MetricName\":\"CPUUtilization\",\"Namespace\":\"AWS/ECS\",\"StatisticType\":\"Statistic\",\"Statistic\":\"MAXIMUM\",\"Unit\":null,\"Dimensions\":[{\"value\":\"filethis-ecs-production\",\"name\":\"ClusterName\"},{\"value\":\"fetcher-aio\",\"name\":\"ServiceName\"}],\"Period\":60,\"EvaluationPeriods\":1,\"ComparisonOperator\":\"GreaterThanThreshold\",\"Threshold\":50.0,\"TreatMissingData\":\"\",\"EvaluateLowSampleCountPercentile\":\"\"}}",
                "Timestamp": "2019-03-08T03:02:47.449Z",
                "SignatureVersion": "1",
                "Signature": "a7DorfPGJAZuvtFsQ95MK/VJB45hQd9dRMrqTb0WherBBCuqUdQvfrv48YdhfDqxm76kjGJKUTGl8jiuJb0kp4upv7Vlrp5lMoRNGbvT6rH1giR54/Hp/JP6oJQ9Pv4P6EAtYeXQ1UXR3ZyhmcWftMXktYANBJsGY/nSxpobHDa4k90oW0deVRLHEzh/37NhzdeoucyR7M1z1+oA5B9Mjl8CizzG0ddgO06tAQlG+HuInqXjoyfYcX2ntg3t/LTF/5qGa5oMb8ti5kVIQSOKHKhe3YNez6YfEJ6bsjaH32Lgq2jjIVxktZGYj5NPjWrVuj8PFKL+bQhsyNkC0vWinQ==",
                "SigningCertUrl": "https://sns.us-west-1.amazonaws.com/SimpleNotificationService-6aad65c2f9911b05cd53efda11f913f9.pem",
                "UnsubscribeUrl": "https://sns.us-west-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-west-1:287332224621:Cloudwatch-Alarm-Critical:9a2f4edd-dfeb-45f6-b4be-0ee61734ed61",
                "MessageAttributes": {}
            }
        }
    ]
}

2019-03-08T03:02:48.953Z	f796e599-daa2-4186-8a78-42f190b9a578	Error rendering chart: { AccessDeniedException: User: arn:aws:sts::287332224621:assumed-role/lambda_cs2slack_execution_role/cloudWatchToSlackWithGraphCritical is not authorized to perform: logs:DescribeMetricFilters on resource: arn:aws:logs:us-east-1:287332224621:log-group:null:log-stream:
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'User: arn:aws:sts::287332224621:assumed-role/lambda_cs2slack_execution_role/cloudWatchToSlackWithGraphCritical is not authorized to perform: logs:DescribeMetricFilters on resource: arn:aws:logs:us-east-1:287332224621:log-group:null:log-stream:',
code: 'AccessDeniedException',
time: 2019-03-08T03:02:48.953Z,
requestId: 'a7c41254-414e-11e9-917e-c7aababf3797',
statusCode: 400,
retryable: false,
retryDelay: 77.44985682618575 }
2019-03-08T03:02:48.972Z	f796e599-daa2-4186-8a78-42f190b9a578	Sending Slack message from Parser[cloudwatch]:
{
    "attachments": [
        {
            "fallback": "PROD-fetcher-cpu-max state is now ALARM:\nThreshold Crossed: 1 datapoint [165.95022984554893 (08/03/19 03:01:00)] was greater than the threshold (50.0).",
            "color": "danger",
            "author_name": "AWS CloudWatch Alarm (287332224621)",
            "title": "PROD-fetcher-cpu-max",
            "title_link": "https://console.aws.amazon.com/cloudwatch/home?region=us-west-1#alarm:name=PROD-fetcher-cpu-max",
            "text": "Threshold Crossed: 1 datapoint [165.95022984554893 (08/03/19 03:01:00)] was greater than the threshold (50.0).",
            "fields": [
                {
                    "title": "State Change",
                    "value": "OK → ALARM",
                    "short": true
                },
                {
                    "title": "Region",
                    "value": "US West (N. California)",
                    "short": true
                }
            ],
            "ts": 1552014167,
            "footer": "Received via <https://console.aws.amazon.com/sns/v2/home?region=us-west-1#/topics/arn:aws:sns:us-west-1:287332224621:Cloudwatch-Alarm-Critical|SNS Cloudwatch-Alarm-Critical> | <https://287332224621.signin.aws.amazon.com/console/sns?region=us-west-1|Sign-In>"
        }
    ]
}

2019-03-08T03:02:49.323Z	f796e599-daa2-4186-8a78-42f190b9a578	Message posted successfully.
END RequestId: f796e599-daa2-4186-8a78-42f190b9a578
REPORT RequestId: f796e599-daa2-4186-8a78-42f190b9a578	Duration: 1104.37 ms	Billed Duration: 1200 ms Memory Size: 256 MB	Max Memory Used: 95 MB

**Comment by claylehman** [comment]
I see its missing a permission...thanks for pointing me in the right direction...i will work though this

**Comment by claylehman** [comment]
OK...permissions issue seems cleaned up. Still getting an error.  "Error rendering chart: Cannot render a chart without timeframe"

Full log for invocation below:

START RequestId: 639bef28-6f33-4351-a768-31d44fd0e42b Version: $LATEST
2019-03-08T03:21:23.214Z	639bef28-6f33-4351-a768-31d44fd0e42b	Incoming Message:
{
    "Records": [
        {
            "EventSource": "aws:sns",
            "EventVersion": "1.0",
            "EventSubscriptionArn": "arn:aws:sns:us-west-1:287332224621:Cloudwatch-Alarm-Critical:9a2f4edd-dfeb-45f6-b4be-0ee61734ed61",
            "Sns": {
                "Type": "Notification",
                "MessageId": "625c78bc-2a2c-5d4f-ba26-2c47cbdea7b5",
                "TopicArn": "arn:aws:sns:us-west-1:287332224621:Cloudwatch-Alarm-Critical",
                "Subject": "ALARM: \"PROD-ingester-cpu-max\" in US West (N. California)",
                "Message": "{\"AlarmName\":\"PROD-ingester-cpu-max\",\"AlarmDescription\":\"This metric monitors ingester CPU max\",\"AWSAccountId\":\"287332224621\",\"NewStateValue\":\"ALARM\",\"NewStateReason\":\"Threshold Crossed: 1 datapoint [76.79715665390617 (08/03/19 03:19:00)] was greater than the threshold (4.0).\",\"StateChangeTime\":\"2019-03-08T03:21:22.891+0000\",\"Region\":\"US West (N. California)\",\"OldStateValue\":\"OK\",\"Trigger\":{\"MetricName\":\"CPUUtilization\",\"Namespace\":\"AWS/ECS\",\"StatisticType\":\"Statistic\",\"Statistic\":\"MAXIMUM\",\"Unit\":null,\"Dimensions\":[{\"value\":\"ingester-aio\",\"name\":\"ServiceName\"},{\"value\":\"filethis-ecs-production\",\"name\":\"ClusterName\"}],\"Period\":60,\"EvaluationPeriods\":1,\"ComparisonOperator\":\"GreaterThanThreshold\",\"Threshold\":4.0,\"TreatMissingData\":\"\",\"EvaluateLowSampleCountPercentile\":\"\"}}",
                "Timestamp": "2019-03-08T03:21:22.908Z",
                "SignatureVersion": "1",
                "Signature": "R/HCN4zOEg9ruPdA7/5UfWP+UaAic8mz9voigrDDP0N+fpCx/vNa/UMGmdl5KaPs6opty1J99qIWmaS43pun3PKVC7u58RF6um1EY8m2CT4q+Dw/nk8VN7KBYMy+HyB0rOBwYzCx8jIz4b2eF/bPArPaw2p5WWIdQhPKR6R5QfOoNpIwt54O+1RjnF1qFsgPzkdbMDibXcT6d3CJQPJxbHKR3+a6BUslSk7PH2nxBDltmN2e30JJ9uHSAO95veLlEtuqIPG3pqhXmY8JyxvL/0R93UmOxocgQWGVJteO5vibOIo7R+eGy1aArv9N3FTsa3GZQ6iFWgebTbisggK7ng==",
                "SigningCertUrl": "https://sns.us-west-1.amazonaws.com/SimpleNotificationService-6aad65c2f9911b05cd53efda11f913f9.pem",
                "UnsubscribeUrl": "https://sns.us-west-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-west-1:287332224621:Cloudwatch-Alarm-Critical:9a2f4edd-dfeb-45f6-b4be-0ee61734ed61",
                "MessageAttributes": {}
            }
        }
    ]
}

2019-03-08T03:21:23.590Z	639bef28-6f33-4351-a768-31d44fd0e42b	Error rendering chart: Cannot render a chart without timeframe
2019-03-08T03:21:23.590Z	639bef28-6f33-4351-a768-31d44fd0e42b	Sending Slack message from Parser[cloudwatch]:
{
    "attachments": [
        {
            "fallback": "PROD-ingester-cpu-max state is now ALARM:\nThreshold Crossed: 1 datapoint [76.79715665390617 (08/03/19 03:19:00)] was greater than the threshold (4.0).",
            "color": "danger",
            "author_name": "AWS CloudWatch Alarm (287332224621)",
            "title": "PROD-ingester-cpu-max",
            "title_link": "https://console.aws.amazon.com/cloudwatch/home?region=us-west-1#alarm:name=PROD-ingester-cpu-max",
            "text": "Threshold Crossed: 1 datapoint [76.79715665390617 (08/03/19 03:19:00)] was greater than the threshold (4.0).",
            "fields": [
                {
                    "title": "State Change",
                    "value": "OK → ALARM",
                    "short": true
                },
                {
                    "title": "Region",
                    "value": "US West (N. California)",
                    "short": true
                }
            ],
            "ts": 1552015282,
            "footer": "Received via <https://console.aws.amazon.com/sns/v2/home?region=us-west-1#/topics/arn:aws:sns:us-west-1:287332224621:Cloudwatch-Alarm-Critical|SNS Cloudwatch-Alarm-Critical> | <https://287332224621.signin.aws.amazon.com/console/sns?region=us-west-1|Sign-In>"
        }
    ]
}

2019-03-08T03:21:23.838Z	639bef28-6f33-4351-a768-31d44fd0e42b	Message posted successfully.
END RequestId: 639bef28-6f33-4351-a768-31d44fd0e42b
REPORT RequestId: 639bef28-6f33-4351-a768-31d44fd0e42b	Duration: 821.82 ms	Billed Duration: 900 ms Memory Size: 256 MB	Max Memory Used: 97 MB

**Comment by homeyjd** [comment]
@claylehman Lots of detail here, thanks!

**RE: Permissions**
The [`cloudformation.yml`](https://github.com/arabold/aws-to-slack/blob/master/cloudformation.yaml#L69) stack adds `arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess` which includes `"logs:Describe*"` on `*`.  This should have cleared up any permissions issues.  You mentioned you used Terraform to create the stack -- make sure to add this managed policy :).

**RE: Cannot render chart without timeframe**
My first thought would be that there isn't any data.  The chart is based on the timing of the metric events it receives.  If there are no data points, then it can't generate a chart.  This would happen if you selected "missing" or "bad" for "Treat missing data as"; your alarm would enter the alert state when there are actually no data points.

I've added a custom error message to `master` to notate this edge case: https://github.com/arabold/aws-to-slack/commit/c44aac084177a20a8355f6c05bf2faf744b87361

Hope this helps!

**Comment by homeyjd** [comment]
@claylehman I found a case where `region` would ALWAYS be defaulted back to us-east-1, which causes an empty dataset instead of a failure! (Seems strange to not fail -- one might think the API would return failure since the metric was not defined in that region?)

I've pushed a new commit that fixes cross-region lookups: https://github.com/arabold/aws-to-slack/commit/450910a9512063459097baa58e9f4097bc76f2e2
Thanks for pointing this out -- I was suddenly having the same problem and led me in the right direction.

**Comment by claylehman** [comment]
that fixed it for me, you are awesome! thanks!

![image](https://user-images.githubusercontent.com/40699759/54429617-66f96e80-46f7-11e9-8a5f-6f4d288f8a39.png)

**Comment by jangsub-choi** [comment]
I can't see the chart in the same way. Can I still ask more about this issue?
