### ISSUE TITLE
Support for Auto Scale notifications

### ISSUE THREAD

**Issue by arabold** [arabold/aws-to-slack#5]

**Comment by nickallevato** [comment]
Is this recent? Looks like it. Love this project and I think I can contribute what I put together for my team's own needs. Primitive-as-would-imagine but willing to make this my baby as much as a can.

@arabold thanks for taking the time on this project. Gonna get some dinner and coffee and put together something for you to review. Thanks again!

![image](https://user-images.githubusercontent.com/6791120/29746540-2ae26cf8-8a92-11e7-9ee4-f34dad282d79.png)

**Comment by arabold** [comment]
Hi @nickallevato , I'm happy for any help. If you have any ideas, feature requests, or even better a pull request, let me know. The open tasks here in this list are basically serving as a to do list for the project.

**Comment by homeyjd** [comment]
I've included an AutoScaling parser on my branch: 
https://github.com/homeyjd/aws-to-slack/blob/master/src/parsers/autoscaling.js
Included in PR:
https://github.com/arabold/aws-to-slack/pull/35

**Comment by sopel** [comment]
Thanks for implementing the Auto Scaling parser @homeyjd, this issue can be closed then I presume?

**Comment by homeyjd** [comment]
Seems so :)
