### ISSUE TITLE
Template on AWS is not updated for new Node version

### ISSUE THREAD

**Issue by elChapoSing** [arabold/aws-to-slack#55]
Getting this error when trying to launch the stack from the S3 template : 

`The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 1184b2c9-7840-11e9-a662-eb416f189a16) `

**Comment by homeyjd** [comment]
The S3 template?  The `cloudformation.yaml` file usese the nodejs8.10 runtime:
https://github.com/arabold/aws-to-slack/blob/master/cloudformation.yaml#L51
What template are you referring to?

**Comment by homeyjd** [comment]
Duh... the links in the `readme` point to S3...  Hmm, need to update the ReadMe.  Those S3 buckets are the ones no one has write access to!

**Comment by elChapoSing** [comment]
yes the s3 template that you get when trying to launch the stack from the
buttons in the readme on github.

**Comment by elChapoSing** [comment]
yes ended up manually copying the yaml from github to launch the stack but
should probably be automatic :)

**Comment by homeyjd** [comment]
For now, I've removed the S3 links to avoid confusion.  Future state, it'd be great to have a sponsor for some new S3 buckets (or to have @arabold share creds!)
