### ISSUE TITLE
metrics graph is not showing in slack

### ISSUE THREAD

**Issue by emzfuu** [arabold/aws-to-slack#61]
Hi I successfully integrated cloudwatch to slack but the problem is metrics graph is not showing in slack. Please help

**Comment by homeyjd** [comment]
First debugging place is Lambda logs.  What errors do you see there?

**Comment by conraddd** [comment]
same here, I see an empty "image_url" from Lambda log

**Comment by homeyjd** [comment]
Closing due to missing stack traces or logs.
