### ISSUE TITLE
Codebase version in the yaml template ?

### ISSUE THREAD

**Issue by elChapoSing** [arabold/aws-to-slack#62]
Is this where the codebase is defined ?

```
Code:
        S3Bucket: !Sub 'aws-to-slack-${AWS::Region}'
        S3Key: release.zip
```

When launching the template, I do not get the latest version of the code. Has this been updated for all regions ?
If I'm supposed to update the function code some other way, how to proceed ?

**Comment by homeyjd** [comment]
Only @arabold has access to the S3 buckets and we haven't seen him in some time.  

I've updated the readme with some additional options: https://github.com/arabold/aws-to-slack#try
