### ISSUE TITLE
Slack running out of memory/timeout

### ISSUE THREAD

**Issue by lehneres** [arabold/aws-to-slack#63]
We are currently seeing an issue with aws2slack where Lambdas would fail due to timeouts (30s). It seems this is somehow related to memory consumption as it will use all available memory at this point:

`06:26:20REPORT RequestId: 4a1e0e6e-5bd7-4951-b3df-b701d8e5d8a5	Duration: 30030.25 ms	Billed Duration: 30000 ms Memory Size: 256 MB	Max Memory Used: 256 MB

06:26:20 2019-06-12T06:26:20.256Z 4a1e0e6e-5bd7-4951-b3df-b701d8e5d8a5 Task timed out after 30.03 seconds`

sometimes also this message is logged:

`06:27:34 REPORT RequestId: 4a1e0e6e-5bd7-4951-b3df-b701d8e5d8a5	Duration: 18887.18 ms	Billed Duration: 18900 ms Memory Size: 256 MB	Max Memory Used: 257 MB

06:27:34 RequestId: 4a1e0e6e-5bd7-4951-b3df-b701d8e5d8a5 Error: Runtime exited with error: signal: killed Runtime.ExitError`

It happens quite often, however in between there are successful calls.

Any idea what could cause the timeout and the high memory consumption?

EDIT: Same input works when running locally...

**Comment by homeyjd** [comment]
Thanks for reporting!
This repo has changed significantly in the last 6mo, notably upgrading to async/await and requiring Node v8.10 on Lambda. 
Are you running a recent build of aws-to-slack?

**Comment by alberts-s** [comment]
@homeyjd I was able to also witness this on top of master branch. Adjusting the function memory to 2048M did not resolve the issue.
I will comment here when I have any information on how to reliably reproduce the issue.

**Comment by homeyjd** [comment]
Please include the source event so we know what module is being triggered when this occurs.

**Comment by lehneres** [comment]
Ok, I found the issue. It's within `chart.js` of the cloudwatch parser. It gets stuck in an infinity for loop when there is only a single datapoint in the time series with `fromTime == toTime` and `(toTime - fromTime) / this.chartSamples` evaluating to `0`.

Potential fix in #64 . But not sure if this situation shouldn't be addressed in a proper way.

**Comment by homeyjd** [comment]
Really great catch @lehneres!
Seems that bug has been lurking for a while:
https://github.com/arabold/aws-to-slack/blob/a2ba8aca10b50316b49253fd25ed04c61e08aa3d/src/parsers/cloudwatch/chart.js#L325

I put a slightly more complex gate around the logic that lowers the sample size and increases the time-slot window.  
https://github.com/arabold/aws-to-slack/commit/3078547fb24c055e5da299a9d9fcc1b8f35ada39

This important enough for a point release for sure:
https://github.com/arabold/aws-to-slack/releases/tag/1.2.1

**Comment by j-sim** [comment]
REPORT RequestId: e8230c23-b250-400e-842d-45efff8da2e8	Duration: 180217.76 ms	Billed Duration: 180218 ms	Memory Size: 2048 MB	Max Memory Used: 2048 MB	Init Duration: 1486.72 ms	
RequestId: e8230c23-b250-400e-842d-45efff8da2e8 Error: Runtime exited with error: signal: killed
Runtime.ExitError


Erreur car la lambda utilise trop de RAM
