### ISSUE TITLE
'make deploy' adds lines to TARGET file prefixed by '-e'

### ISSUE THREAD

**Issue by whereisaaron** [arabold/aws-to-slack#66]
The `Makefile` includes some `echo -e` commands to add to the target file. The `-e` seems to work and the backslashes get interpreted, but also the '-e' is turning up in the output added to the file. Can't explain that. Any idea?

```
-e # Makefile on Sat Jul  6 13:04:24 DST 2019
STACK_ID=arn:aws:cloudformation:...
-e # Makefile on Sat Jul  6 13:04:26 DST 2019
LAMBDA_NAME=aws-to-slack-ABCDEFGIJK
```

`echo` is working as you'd expect on the command line.
```
$ echo "Foo\nBar"
Foo\nBar
$ echo -e "Foo\nBar"
Foo
Bar
```

```
GNU Make 4.1
GNU bash, version 4.4.19(1)-release
```

**Comment by homeyjd** [comment]
I'm on `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)`, but bash's inconsistencies might as well be legendary...

Removed the `-e` here: https://github.com/arabold/aws-to-slack/commit/8c0bd929a37532fdd508f15ecdcabbbee24d955d. Does this work on your version?

**Comment by whereisaaron** [comment]
Thanks @homeyjd, considering there are more that *10 years* of development between your version of `bash` and my version, I wouldn't be surprised!

However, I don't think `bash` is the issue here, rather I think the commands in the `Makefile` are being run with pure `sh` and its `echo` does not have the `-e` option.
```
$ echo -e Hello
Hello
$ sh
$ echo -e Hello
-e Hello
```
Your `make` may be using `bash` instead of `sh`. Either way your patch should make it safe!

BTW MacOS is stuck on 3.2 because Apple apparently [ still thinks open source is evil](http://meta.ath0.com/2012/02/05/apples-great-gpl-purge/), but you can actually [upgrade to a modern version of `bash` on MacOS with Homebrew](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba).

> Mavericks ships with bash 3.2. That’s from 2006. The current version is 4.2.10. Why no upgrade? Because Apple’s shipping the last version of bash that was under the GPL version 2.

**Comment by homeyjd** [comment]
Thanks for sharing the context @whereisaaron :)

**Comment by whereisaaron** [comment]
Thanks for putting this project together @homeyjd! I like the parser list with both the select and parse passes. It is the exact same approach as another (unrelated) project I've work on for ~13 years and it really worked as a clean model through many changes over the years.
