### ISSUE TITLE
How to send just a text message?

### ISSUE THREAD

**Issue by ernievd** [arabold/aws-to-slack#69]
I am not sure how I would just have this send out a text message that I can preconfigure?

Is there a variable I should populate?

I want to send a message like "Backup failed" to slack when an alarm is triggered and I have that alarm trigger sns. Nothing fancy needed. How can I use the "Test" feature in Lambda to try this?

Thanks!
Ernie

**Comment by homeyjd** [comment]
This repo parses existing events from AWS services.  That way we don't have to provide explicit text for every possible message type.

From your description, it sounds like you want to be notified when your alarm is triggered.  The CloudFormation template creates an SNS Topic.  You modify your alarm to publish to this SNS Topic.  It's in the section "Actions" near the bottom of the Alarm's edit page.  Done!

If you still want to customize the message that gets sent to SNS, then you need to create a CloudWatch "Rule" (in the menu on the left "Events" => "Rules").  Rules filter events by looking for patterns, then emit a custom event to a destination SNS Topic.  You could use this to push just the text "Backup failed", but I'd skip this step if the alarm is already named "BackupFailedAlarm" (or something like that).
