### ISSUE TITLE
Show alarm threshold in graph

### ISSUE THREAD

**Issue by arabold** [arabold/aws-to-slack#7]
The alarm threshold should be visible in the rendered graph.

**Comment by homeyjd** [comment]
FYI I was able to accomplish this with a .5-point dotted line that replicates the existing dataset.
https://github.com/homeyjd/aws-to-slack/blob/master/src/parsers/cloudwatch/chart.js#L354

**Comment by arabold** [comment]
Very cool. Looks simple enough. Did you test this in different scenarios and would you mind creating a PR?

**Comment by homeyjd** [comment]
It is rolled into https://github.com/arabold/aws-to-slack/pull/35
I know large PRs are hard to grok, I was just trying to efficient with my time :-/. That PR tracks my master branch.

**Comment by homeyjd** [comment]
@arabold, I am only testing one “Sum” scenario right now. My AWS account only has one CW Alarm in breaching state. Would love more example events!

**Comment by homeyjd** [comment]
Updated the screenshot to include threshold.  Thoughts?
https://github.com/homeyjd/aws-to-slack/commit/5ea28c29bd3b8844384e34eca3e8adb9b8ad9069?short_path=f81cafc#diff-f81cafc4734713396f12a35781b73e18

**Comment by homeyjd** [comment]
PR was merged, this is looking good!
