### ISSUE TITLE
Add release.zip to the 1.2.x releases

### ISSUE THREAD

**Issue by maltekrupa** [arabold/aws-to-slack#73]
Hi,

the 1.1.x releases had an `release.zip` already present with the required dependencies in the `build` directory. Would it be possible to add it to the 1.2.x releases as well?

Thanks.

**Comment by homeyjd** [comment]
Sure https://github.com/arabold/aws-to-slack/commit/239315540ce91132fd01a15a63ad009d1bf6bbde

**Comment by homeyjd** [comment]
What am I thinking...
I'll just add the zip to the release.  https://github.com/arabold/aws-to-slack/releases/tag/1.3.0
