### ISSUE TITLE
Codebuild URL format has changed

### ISSUE THREAD

**Issue by wryun** [arabold/aws-to-slack#76]
Old:

https://github.com/arabold/aws-to-slack/blob/0100a3c8cebceef200cc85e021e68b7558e75be6/src/parsers/codebuild.js#L13

New:

https://console.aws.amazon.com/codesuite/codebuild/projects/[my-project]/build/[my-project:build-id]/?region=[region]

**Comment by lorengordon** [comment]
Thanks for the prompt, the broken link was starting to annoy me also, https://github.com/arabold/aws-to-slack/pull/77. :)

**Comment by lorengordon** [comment]
Hi @homeyjd would you mind pushing a bugfix release to include this patch?

**Comment by homeyjd** [comment]
Released! https://github.com/arabold/aws-to-slack/releases/tag/1.3.0
