### ISSUE TITLE
Support for KMS to encrypt environment variables

### ISSUE THREAD

**Issue by arabold** [arabold/aws-to-slack#8]
Currently all environment variables are stored in plain text. That's pretty stupid... We should store it encrypted instead for better security.

**Comment by homeyjd** [comment]
Environment variables currently used:
- `SLACK_CHANNEL` - not-so-secret metadata, probably not a target for encryption?
- `SLACK_HOOK_URL` - endpoint _and_ credential

When KMS encrypts values, the key is stored within the base64-encoded blob.  Thankfully, the above values aren't very long, so if the value is 3-5x longer than normal, we can safely assume it's a KMS-encrypted value.

I've added support here: https://github.com/homeyjd/aws-to-slack/commit/62fe0142abc8972e29351c4c75c92b0f0f80e700
On PR here: https://github.com/arabold/aws-to-slack/pull/35

**Comment by homeyjd** [comment]
Fixed here: https://github.com/arabold/aws-to-slack/pull/58
