### ISSUE TITLE
Access Denied To you Launch Stack

### ISSUE THREAD

**Issue by gsogol** [arabold/aws-to-slack#9]
When trying to launch a template, says access denied to your s3 bucket. Although I can clone, would rather go straight to the source. Thanks.

**Comment by arabold** [comment]
Thanks for the report and sorry for the slow reply. I didn't configure this repo properly to actively notify me on new issues 😞 . This issue should be fixed now, both the stack and the `release.zip` have public read access now.

**Comment by arabold** [comment]
I'm gonna close this. Let me know if you encounter any more issues.
